name: CI

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
    - uses: actions/setup-node@master
    - name: lint all markdownfiles
      run: |
        npm install
        npx markdownlint '**/*.md' --ignore node_modules -c .markdownlint.json